export const productData = [
  {
    product_id: "PR91942",
    name: "AMERICAN GREETINGS Rainbow Latex Balloons| Pack of 20 | Party Decor",
    price: 439.7,
    stock: 9789,
    rating: 1.2,
    weight: 31,
    dimensions: "50cm L x 53cm W x 59cm H",
    color: "Khaki",
    age: "7-10",
    category: "action figures & playsets",
    brand: "barbie"
  },
  {
    product_id: "PR05209",
    name: "Fun2Give Pop-It-Up Dollhouse Tent with House Playmat Playhouse",
    price: 1863.79,
    stock: 493,
    rating: 3.9,
    weight: 9,
    dimensions: "09cm L x 58cm W x 61cm H",
    color: "Maroon",
    age: "0-2",
    category: "games & puzzles",
    brand: "barbie"
  },
  {
    product_id: "PR68988",
    name:
      "Craft-tastic – Kindness Kit – Craft Kit Includes 8 Projects to Inspire Kindness, Bilingual",
    price: 938.53,
    stock: 4911,
    rating: 1.3,
    weight: 11,
    dimensions: "29cm L x 18cm W x 15cm H",
    color: "Pink",
    age: "10+",
    category: "vehicles and remote controls",
    brand: "marvel"
  },
  {
    product_id: "PR10075",
    name: "COBI Small Army A12 Matilda Tank",
    price: 311.2,
    stock: 7712,
    rating: 4.5,
    weight: 46,
    dimensions: "31cm L x 56cm W x 35cm H",
    color: "Violet",
    age: "3-6",
    category: "action figures & playsets",
    brand: "barbie"
  },
  {
    product_id: "PR35251",
    name:
      "EMD GP40 Diesel Locomotive UNION PACIFIC #508 (without dynamic brakes) - N Scale",
    price: 4951.51,
    stock: 6246,
    rating: 0.2,
    weight: 40,
    dimensions: "28cm L x 66cm W x 32cm H",
    color: "Aquamarine",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "play-doh"
  },
  {
    product_id: "PR29726",
    name: "Florida-Opoly",
    price: 2441.67,
    stock: 255,
    rating: 0.6,
    weight: 39,
    dimensions: "60cm L x 90cm W x 48cm H",
    color: "Green",
    age: "7-10",
    category: "games & puzzles",
    brand: "marvel"
  },
  {
    product_id: "PR67933",
    name:
      "Bachmann Old-Time Box Car - Pennsylvania LINES - N Scale, Prototypical Oxide Red",
    price: 1723.6,
    stock: 8105,
    rating: 3.1,
    weight: 47,
    dimensions: "40cm L x 51cm W x 16cm H",
    color: "Teal",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "play-doh"
  },
  {
    product_id: "PR18886",
    name:
      "Nick Jr. Dora the Explorer Child's Dora Costume with Backpack, Small",
    price: 4467.17,
    stock: 1201,
    rating: 2.2,
    weight: 92,
    dimensions: "30cm L x 31cm W x 96cm H",
    color: "Purple",
    age: "3-6",
    category: "action figures & playsets",
    brand: "barbie"
  },
  {
    product_id: "PR66079",
    name: "Klutz Decorate This Journal Toy",
    price: 2294.74,
    stock: 469,
    rating: 2.7,
    weight: 41,
    dimensions: "12cm L x 43cm W x 15cm H",
    color: "Puce",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "hot wheels"
  },
  {
    product_id: "PR57524",
    name: "Fashion Angels We Smell Sweet Bracelet Kit, Assorted",
    price: 2209.48,
    stock: 9263,
    rating: 2.6,
    weight: 91,
    dimensions: "29cm L x 65cm W x 14cm H",
    color: "Aquamarine",
    age: "7-10",
    category: "games & puzzles",
    brand: "disney"
  },
  {
    product_id: "PR32085",
    name:
      "American Girl WellieWishers Garden Adventure Picnic for WellieWisher Dolls",
    price: 3487.45,
    stock: 5250,
    rating: 3.4,
    weight: 29,
    dimensions: "59cm L x 83cm W x 90cm H",
    color: "Indigo",
    age: "3-6",
    category: "building sets & blocks",
    brand: "play-doh"
  },
  {
    product_id: "PR86678",
    name: "Nerf Sports Pro Grip Football (blue football)",
    price: 564.67,
    stock: 5885,
    rating: 2.6,
    weight: 85,
    dimensions: "45cm L x 66cm W x 19cm H",
    color: "Teal",
    age: "7-10",
    category: "building sets & blocks",
    brand: "disney"
  },
  {
    product_id: "PR09802",
    name: "Silver Glitter Hanging Fans (4 ct)",
    price: 1045.07,
    stock: 7954,
    rating: 1,
    weight: 57,
    dimensions: "22cm L x 62cm W x 22cm H",
    color: "Puce",
    age: "7-10",
    category: "vehicles and remote controls",
    brand: "lego"
  },
  {
    product_id: "PR49880",
    name:
      "Entertainment Earth Designer Series Wonder Woman by Darwyn Cooke Action Figure",
    price: 3692.62,
    stock: 8995,
    rating: 4.8,
    weight: 98,
    dimensions: "81cm L x 23cm W x 35cm H",
    color: "Khaki",
    age: "3-6",
    category: "baby, toddler, & preschool learning toys",
    brand: "others"
  },
  {
    product_id: "PR24283",
    name: "Creativity for Kids Clay Keychains",
    price: 1134.92,
    stock: 2522,
    rating: 0.4,
    weight: 57,
    dimensions: "38cm L x 91cm W x 17cm H",
    color: "Violet",
    age: "7-10",
    category: "baby, toddler, & preschool learning toys",
    brand: "disney"
  },
  {
    product_id: "PR17076",
    name:
      "Loftus SW-0249 4 Pc Classic Wooden Games in A Tin Set, 6 inches Long, Brown",
    price: 4598.24,
    stock: 5137,
    rating: 3.7,
    weight: 94,
    dimensions: "78cm L x 03cm W x 79cm H",
    color: "Teal",
    age: "7-10",
    category: "kids arts and crafts",
    brand: "barbie"
  },
  {
    product_id: "PR31676",
    name:
      "AMERICAN GREETINGS Bright Colors Latex Balloons | Pack of 15 | Party Decor",
    price: 3238.2,
    stock: 4793,
    rating: 0.4,
    weight: 77,
    dimensions: "49cm L x 86cm W x 49cm H",
    color: "Blue",
    age: "0-2",
    category: "action figures & playsets",
    brand: "lego"
  },
  {
    product_id: "PR12686",
    name: "Medieval Princess Fuschia Child Costume",
    price: 3746.75,
    stock: 6984,
    rating: 2.9,
    weight: 96,
    dimensions: "25cm L x 47cm W x 62cm H",
    color: "Orange",
    age: "10+",
    category: "action figures & playsets",
    brand: "play-doh"
  },
  {
    product_id: "PR61925",
    name: "Crate Creatures Surprise- Blizz",
    price: 2615.13,
    stock: 1096,
    rating: 0.3,
    weight: 14,
    dimensions: "15cm L x 00cm W x 45cm H",
    color: "Mauv",
    age: "0-2",
    category: "action figures & playsets",
    brand: "funko"
  },
  {
    product_id: "PR86512",
    name: "Play-Doh Poop Troop Set with 12 Cans",
    price: 2123.79,
    stock: 7635,
    rating: 2,
    weight: 7,
    dimensions: "09cm L x 77cm W x 84cm H",
    color: "Turquoise",
    age: "3-6",
    category: "dolls, collectibles, and stuffed animals",
    brand: "others"
  },
  {
    product_id: "PR10483",
    name:
      "up4 Mickey Grab N Go Play Pack 8.50x5.25x0.5 [Contains 8 Retail (S) Per SKU# 1051224, Multicolor",
    price: 3171.39,
    stock: 7983,
    rating: 0.2,
    weight: 84,
    dimensions: "55cm L x 83cm W x 31cm H",
    color: "Indigo",
    age: "3-6",
    category: "baby, toddler, & preschool learning toys",
    brand: "hot wheels"
  },
  {
    product_id: "PR41597",
    name: "DreamWorks Trolls Biggie Talkin’ Troll Plush Doll",
    price: 3233.02,
    stock: 6078,
    rating: 1.4,
    weight: 61,
    dimensions: "26cm L x 70cm W x 04cm H",
    color: "Yellow",
    age: "0-2",
    category: "games & puzzles",
    brand: "others"
  },
  {
    product_id: "PR91833",
    name:
      "Entertainment Earth Batman Black & White 1st Appearance by Bob Kane Figure",
    price: 3232.56,
    stock: 9424,
    rating: 0.5,
    weight: 92,
    dimensions: "78cm L x 15cm W x 68cm H",
    color: "Teal",
    age: "0-2",
    category: "action figures & playsets",
    brand: "funko"
  },
  {
    product_id: "PR27626",
    name: "Florida-Opoly",
    price: 4027.11,
    stock: 255,
    rating: 0.7,
    weight: 39,
    dimensions: "78cm L x 04cm W x 50cm H",
    color: "Green",
    age: "3-6",
    category: "action figures & playsets",
    brand: "others"
  },
  {
    product_id: "PR26218",
    name: "GreenBrier Games Yashima Legends from Fairytale Board Game",
    price: 2011.23,
    stock: 5498,
    rating: 1,
    weight: 56,
    dimensions: "38cm L x 75cm W x 25cm H",
    color: "Khaki",
    age: "10+",
    category: "dolls, collectibles, and stuffed animals",
    brand: "hot wheels"
  },
  {
    product_id: "PR47586",
    name: "Delta Children Bistro 2-Piece Chair Set, White with Driftwood",
    price: 4079.74,
    stock: 2441,
    rating: 4.6,
    weight: 62,
    dimensions: "50cm L x 66cm W x 88cm H",
    color: "Orange",
    age: "0-2",
    category: "baby, toddler, & preschool learning toys",
    brand: "hot wheels"
  },
  {
    product_id: "PR32592",
    name: "Costume Sunglasses Clown from IT Sun-Staches Party Favors UV400",
    price: 3030.57,
    stock: 5871,
    rating: 3.3,
    weight: 20,
    dimensions: "73cm L x 58cm W x 63cm H",
    color: "Aquamarine",
    age: "0-2",
    category: "action figures & playsets",
    brand: "marvel"
  },
  {
    product_id: "PR03911",
    name: "Barbie Outdoor Furniture Set, Brick Pizza Oven",
    price: 721.63,
    stock: 935,
    rating: 1.2,
    weight: 47,
    dimensions: "37cm L x 56cm W x 04cm H",
    color: "Maroon",
    age: "7-10",
    category: "baby, toddler, & preschool learning toys",
    brand: "play-doh"
  },
  {
    product_id: "PR20702",
    name:
      "LEGO Minecraft Creeper BigFig and Ocelot Characters 21156 Buildable Toy Minecraft Figure Gift Set for Play and Decoration, New 2020 (184 Pieces)",
    price: 2094.33,
    stock: 3157,
    rating: 4.5,
    weight: 99,
    dimensions: "08cm L x 78cm W x 71cm H",
    color: "Crimson",
    age: "7-10",
    category: "games & puzzles",
    brand: "disney"
  },
  {
    product_id: "PR96953",
    name: "Forum Novelties Children's Unisex Headless Costume",
    price: 155,
    stock: 7121,
    rating: 3.3,
    weight: 33,
    dimensions: "92cm L x 85cm W x 50cm H",
    color: "Teal",
    age: "10+",
    category: "action figures & playsets",
    brand: "lego"
  },
  {
    product_id: "PR15670",
    name: "Hey! Play! Kids Pop-up Six-sided Ball Pit Tent",
    price: 2919.67,
    stock: 9468,
    rating: 1.7,
    weight: 85,
    dimensions: "03cm L x 37cm W x 36cm H",
    color: "Violet",
    age: "0-2",
    category: "baby, toddler, & preschool learning toys",
    brand: "hot wheels"
  },
  {
    product_id: "PR14538",
    name:
      "Carrera 23856 Ferrari 512 S Berlinetta Scuderia Filipinetti #3 1970 Digital 124 Slot Car 1:24 Scale",
    price: 4307.72,
    stock: 3138,
    rating: 3.2,
    weight: 100,
    dimensions: "56cm L x 13cm W x 28cm H",
    color: "Crimson",
    age: "10+",
    category: "vehicles and remote controls",
    brand: "funko"
  },
  {
    product_id: "PR68245",
    name: "4M Glow-In-The-Dark 3D Dinosaur",
    price: 982.88,
    stock: 8318,
    rating: 2,
    weight: 43,
    dimensions: "67cm L x 18cm W x 94cm H",
    color: "Purple",
    age: "7-10",
    category: "action figures & playsets",
    brand: "play-doh"
  },
  {
    product_id: "PR99871",
    name:
      "Melissa & Doug Mine to Love Jordan 12” Baby Doll (Includes Romper, Cap, Pacifier, Great Gift for Girls and Boys - Best for Babies, 18 Month Olds, 24 Month Olds, 1 and 2 Year Olds )",
    price: 2794.92,
    stock: 2210,
    rating: 0.5,
    weight: 13,
    dimensions: "78cm L x 65cm W x 17cm H",
    color: "Orange",
    age: "10+",
    category: "building sets & blocks",
    brand: "hot wheels"
  },
  {
    product_id: "PR85023",
    name: "Anna Frozen Fever Deluxe Costume, One Color, 3T-4T",
    price: 1216.88,
    stock: 5018,
    rating: 1.5,
    weight: 50,
    dimensions: "04cm L x 62cm W x 08cm H",
    color: "Goldenrod",
    age: "10+",
    category: "action figures & playsets",
    brand: "barbie"
  },
  {
    product_id: "PR34147",
    name: "Dickie Toys Air Pump Garbage Truck",
    price: 882.86,
    stock: 975,
    rating: 3.1,
    weight: 100,
    dimensions: "14cm L x 19cm W x 88cm H",
    color: "Teal",
    age: "7-10",
    category: "vehicles and remote controls",
    brand: "funko"
  },
  {
    product_id: "PR69488",
    name: "Colorforms Brand Despicable Me Create a Story Restickable Set",
    price: 1045.11,
    stock: 3205,
    rating: 1.8,
    weight: 29,
    dimensions: "19cm L x 47cm W x 02cm H",
    color: "Mauv",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "play-doh"
  },
  {
    product_id: "PR68824",
    name: "Lord of The Rings Bilbo Baggins Sword",
    price: 622.47,
    stock: 5061,
    rating: 2.6,
    weight: 72,
    dimensions: "01cm L x 50cm W x 47cm H",
    color: "Turquoise",
    age: "0-2",
    category: "action figures & playsets",
    brand: "funko"
  },
  {
    product_id: "PR93523",
    name: "Dragon Ball Fighterz - PlayStation 4",
    price: 2561.66,
    stock: 2249,
    rating: 1.7,
    weight: 57,
    dimensions: "61cm L x 94cm W x 07cm H",
    color: "Aquamarine",
    age: "10+",
    category: "kids arts and crafts",
    brand: "funko"
  },
  {
    product_id: "PR55532",
    name: "Vallejo Umber Wash, 17ml",
    price: 2138.05,
    stock: 2611,
    rating: 1.7,
    weight: 30,
    dimensions: "48cm L x 43cm W x 46cm H",
    color: "Mauv",
    age: "3-6",
    category: "vehicles and remote controls",
    brand: "barbie"
  },
  {
    product_id: "PR39691",
    name: "COBI Historical Collection Battleship Tirpitz",
    price: 3125.55,
    stock: 5939,
    rating: 2.5,
    weight: 77,
    dimensions: "46cm L x 77cm W x 06cm H",
    color: "Red",
    age: "7-10",
    category: "action figures & playsets",
    brand: "disney"
  },
  {
    product_id: "PR40413",
    name: "Mudpuppy Princesses Color in Crowns",
    price: 2368.24,
    stock: 501,
    rating: 4.5,
    weight: 64,
    dimensions: "74cm L x 50cm W x 46cm H",
    color: "Red",
    age: "10+",
    category: "games & puzzles",
    brand: "others"
  },
  {
    product_id: "PR71796",
    name: "Gym Dandy Teeter-Totter Home Seesaw Playground Set TT-210",
    price: 1726.24,
    stock: 8794,
    rating: 3.5,
    weight: 98,
    dimensions: "25cm L x 65cm W x 26cm H",
    color: "Purple",
    age: "0-2",
    category: "baby, toddler, & preschool learning toys",
    brand: "lego"
  },
  {
    product_id: "PR02890",
    name:
      "Mon AMI Pink Piglet Ballerina Designer Plush Doll, Exquisite Craftmanship, Premium Quality, Cuddling, Collecting & Playing Toy, Baby or Toddler Gift 18, Multicolor",
    price: 2992.87,
    stock: 5359,
    rating: 2.2,
    weight: 60,
    dimensions: "99cm L x 08cm W x 36cm H",
    color: "Khaki",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "others"
  },
  {
    product_id: "PR23187",
    name: "Jumbo Foil Star Cutout (gold) Party Accessory (1 count)",
    price: 4124.69,
    stock: 3677,
    rating: 3.5,
    weight: 19,
    dimensions: "84cm L x 44cm W x 13cm H",
    color: "Blue",
    age: "0-2",
    category: "kids arts and crafts",
    brand: "barbie"
  },
  {
    product_id: "PR52653",
    name: "Elenco Breadboard with 830 Tie Points - 9425",
    price: 2890.88,
    stock: 5012,
    rating: 2.1,
    weight: 11,
    dimensions: "42cm L x 84cm W x 93cm H",
    color: "Turquoise",
    age: "0-2",
    category: "building sets & blocks",
    brand: "marvel"
  },
  {
    product_id: "PR39189",
    name:
      "The Corps Special Forces Action Figures & Vehicle Deluxe Playset (Packaging & Colors May Vary)",
    price: 191.92,
    stock: 940,
    rating: 3.4,
    weight: 19,
    dimensions: "49cm L x 82cm W x 33cm H",
    color: "Violet",
    age: "10+",
    category: "action figures & playsets",
    brand: "barbie"
  },
  {
    product_id: "PR76300",
    name:
      "Lionel Racing, Chase Elliott, Napa Nightvision, 2018, Chevrolet Camaro, NASCAR Diecast 1: 24 Scale",
    price: 1637.89,
    stock: 3090,
    rating: 4.9,
    weight: 48,
    dimensions: "42cm L x 93cm W x 58cm H",
    color: "Teal",
    age: "7-10",
    category: "building sets & blocks",
    brand: "disney"
  },
  {
    product_id: "PR10936",
    name:
      "PLUS PLUS - Construction Building Toy, Open Play Set - 3,600 Pieces with Storage Tub - Basic Color Mix",
    price: 3760.06,
    stock: 7029,
    rating: 3,
    weight: 84,
    dimensions: "33cm L x 51cm W x 77cm H",
    color: "Yellow",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "others"
  },
  {
    product_id: "PR89948",
    name:
      "Bachmann Old-Time Box Car - Pennsylvania LINES - N Scale, Prototypical Oxide Red",
    price: 995.1,
    stock: 8105,
    rating: 3.1,
    weight: 47,
    dimensions: "80cm L x 73cm W x 87cm H",
    color: "Teal",
    age: "7-10",
    category: "kids arts and crafts",
    brand: "funko"
  },
  {
    product_id: "PR09151",
    name: "Rubie's Rag Doll Children's Costume",
    price: 4631.09,
    stock: 9661,
    rating: 4.9,
    weight: 27,
    dimensions: "39cm L x 75cm W x 29cm H",
    color: "Yellow",
    age: "7-10",
    category: "games & puzzles",
    brand: "lego"
  },
  {
    product_id: "PR08446",
    name: "NCAA Georgia Bulldogs Toy Puzzle Cube",
    price: 2992.34,
    stock: 8178,
    rating: 3.3,
    weight: 17,
    dimensions: "92cm L x 28cm W x 87cm H",
    color: "Mauv",
    age: "3-6",
    category: "games & puzzles",
    brand: "lego"
  },
  {
    product_id: "PR20980",
    name: "ebba Baby Talk Carrier, My Pirate Ship Playset",
    price: 4178.66,
    stock: 6229,
    rating: 4.1,
    weight: 37,
    dimensions: "52cm L x 80cm W x 42cm H",
    color: "Violet",
    age: "10+",
    category: "baby, toddler, & preschool learning toys",
    brand: "funko"
  },
  {
    product_id: "PR19139",
    name: "Blade 130 S BNF Basic With Safe",
    price: 446.23,
    stock: 867,
    rating: 2.8,
    weight: 91,
    dimensions: "65cm L x 55cm W x 74cm H",
    color: "Aquamarine",
    age: "7-10",
    category: "games & puzzles",
    brand: "play-doh"
  },
  {
    product_id: "PR69109",
    name: "In the Breeze Dragon Twister",
    price: 2414.49,
    stock: 9030,
    rating: 1.7,
    weight: 59,
    dimensions: "72cm L x 74cm W x 17cm H",
    color: "Orange",
    age: "0-2",
    category: "action figures & playsets",
    brand: "others"
  },
  {
    product_id: "PR56781",
    name: "Gowi Toys Austria Police Van with Police Play Figures",
    price: 2033.5,
    stock: 1967,
    rating: 0.9,
    weight: 42,
    dimensions: "76cm L x 64cm W x 96cm H",
    color: "Yellow",
    age: "7-10",
    category: "action figures & playsets",
    brand: "marvel"
  },
  {
    product_id: "PR56940",
    name: "Losi Ride Height Gauge, LOSA99173",
    price: 3323.01,
    stock: 9753,
    rating: 3.6,
    weight: 46,
    dimensions: "90cm L x 19cm W x 53cm H",
    color: "Fuscia",
    age: "7-10",
    category: "action figures & playsets",
    brand: "play-doh"
  },
  {
    product_id: "PR62851",
    name: "Colorbok YPI50047 You Paint It Plaster Kit, Value Pack, Enchanted",
    price: 3277.39,
    stock: 4552,
    rating: 2.7,
    weight: 9,
    dimensions: "10cm L x 55cm W x 33cm H",
    color: "Mauv",
    age: "7-10",
    category: "vehicles and remote controls",
    brand: "play-doh"
  },
  {
    product_id: "PR52990",
    name:
      "Nickelodeon's Dora and the Lost City of Gold Nickelodeon's Dora & The Lost City of Gold: Boots, Multicolor",
    price: 1176.11,
    stock: 7723,
    rating: 1.7,
    weight: 90,
    dimensions: "10cm L x 07cm W x 10cm H",
    color: "Green",
    age: "3-6",
    category: "building sets & blocks",
    brand: "play-doh"
  },
  {
    product_id: "PR74502",
    name:
      "Gorilla Playsets 01-3036-G Malibu Playhouse Wooden Playhouse for Kids, Brown & Green",
    price: 4798.65,
    stock: 258,
    rating: 1.7,
    weight: 41,
    dimensions: "30cm L x 50cm W x 67cm H",
    color: "Orange",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "funko"
  },
  {
    product_id: "PR47057",
    name:
      "Melissa & Doug K’s Kids Whose Tail? 8-Page Soft Activity Book, The Original (Great Gift for Girls and Boys - Best for Babies and Toddlers, All Ages)",
    price: 1361.16,
    stock: 9620,
    rating: 1.8,
    weight: 83,
    dimensions: "69cm L x 03cm W x 00cm H",
    color: "Maroon",
    age: "0-2",
    category: "building sets & blocks",
    brand: "disney"
  },
  {
    product_id: "PR46715",
    name: "ebba Baby Talk Carrier, My Pirate Ship Playset",
    price: 4220.15,
    stock: 6229,
    rating: 0.8,
    weight: 37,
    dimensions: "15cm L x 83cm W x 82cm H",
    color: "Violet",
    age: "10+",
    category: "baby, toddler, & preschool learning toys",
    brand: "barbie"
  },
  {
    product_id: "PR23566",
    name: "Turtle Beach XO Three Gaming Headset for Xbox One",
    price: 553.27,
    stock: 5467,
    rating: 0.2,
    weight: 37,
    dimensions: "24cm L x 77cm W x 35cm H",
    color: "Purple",
    age: "0-2",
    category: "games & puzzles",
    brand: "barbie"
  },
  {
    product_id: "PR56396",
    name: "Fisher-Price Infant-to-Toddler Rocker, Jungle Fun",
    price: 875.1,
    stock: 8696,
    rating: 1.3,
    weight: 82,
    dimensions: "13cm L x 55cm W x 32cm H",
    color: "Pink",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "disney"
  },
  {
    product_id: "PR45343",
    name: "Aurora World Sweet and Softer Perky Penguin 9.5 Plush",
    price: 2821.73,
    stock: 1278,
    rating: 0.2,
    weight: 20,
    dimensions: "96cm L x 50cm W x 41cm H",
    color: "Maroon",
    age: "10+",
    category: "kids arts and crafts",
    brand: "funko"
  },
  {
    product_id: "PR06200",
    name: "Marvel Hulk Fist Pewter Key Ring",
    price: 908.45,
    stock: 1189,
    rating: 3.4,
    weight: 40,
    dimensions: "60cm L x 50cm W x 83cm H",
    color: "Red",
    age: "10+",
    category: "games & puzzles",
    brand: "marvel"
  },
  {
    product_id: "PR13041",
    name: "Snow White and The Huntsman Deluxe Queen Ravenna Costume",
    price: 648,
    stock: 2944,
    rating: 4.9,
    weight: 24,
    dimensions: "48cm L x 01cm W x 48cm H",
    color: "Indigo",
    age: "0-2",
    category: "baby, toddler, & preschool learning toys",
    brand: "lego"
  },
  {
    product_id: "PR87140",
    name: "Transformers Bumblebee Movie Muscle Bumblebee Costume for Infants",
    price: 1749.53,
    stock: 2113,
    rating: 0.5,
    weight: 42,
    dimensions: "49cm L x 26cm W x 82cm H",
    color: "Violet",
    age: "3-6",
    category: "action figures & playsets",
    brand: "barbie"
  },
  {
    product_id: "PR39757",
    name:
      "Badger Basket Chevron Upholstered Doll Sofa with Foldout Bed (fits American Girl Dolls), Pink/White",
    price: 1452.47,
    stock: 8350,
    rating: 2.1,
    weight: 80,
    dimensions: "20cm L x 89cm W x 87cm H",
    color: "Purple",
    age: "0-2",
    category: "baby, toddler, & preschool learning toys",
    brand: "others"
  },
  {
    product_id: "PR32104",
    name:
      "Walthers Cornerstone HO Scale Hardwood Furniture Factory Structure Kit",
    price: 4454.87,
    stock: 2561,
    rating: 1.8,
    weight: 50,
    dimensions: "82cm L x 96cm W x 97cm H",
    color: "Green",
    age: "7-10",
    category: "kids arts and crafts",
    brand: "hot wheels"
  },
  {
    product_id: "PR34616",
    name:
      "Eureka Back to School Gold Glitter Star Stickers for Kids and Teachers, 72pc",
    price: 1111.79,
    stock: 7796,
    rating: 3.8,
    weight: 97,
    dimensions: "11cm L x 06cm W x 81cm H",
    color: "Violet",
    age: "0-2",
    category: "vehicles and remote controls",
    brand: "disney"
  },
  {
    product_id: "PR37370",
    name: "Disney Mickey Golf Ball Spinner Pewter Key Ring Key Accessory",
    price: 1620,
    stock: 7104,
    rating: 2.8,
    weight: 61,
    dimensions: "05cm L x 34cm W x 87cm H",
    color: "Blue",
    age: "0-2",
    category: "games & puzzles",
    brand: "funko"
  },
  {
    product_id: "PR53341",
    name:
      "Melissa & Doug Disney Cinderella Rags to Riches Wooden Magnetic Game With 10 Magnetic Pieces and Wand",
    price: 1548.9,
    stock: 2290,
    rating: 4,
    weight: 97,
    dimensions: "67cm L x 39cm W x 26cm H",
    color: "Pink",
    age: "0-2",
    category: "kids arts and crafts",
    brand: "barbie"
  },
  {
    product_id: "PR39274",
    name: "Bachmann Trains Great Northern Gondola",
    price: 1885.71,
    stock: 4129,
    rating: 4.7,
    weight: 88,
    dimensions: "73cm L x 72cm W x 82cm H",
    color: "Orange",
    age: "10+",
    category: "vehicles and remote controls",
    brand: "funko"
  },
  {
    product_id: "PR32575",
    name: "WWE Rey Mysterio Elite Collection Action Figure",
    price: 2574.56,
    stock: 3968,
    rating: 1.5,
    weight: 62,
    dimensions: "71cm L x 25cm W x 89cm H",
    color: "Mauv",
    age: "10+",
    category: "dolls, collectibles, and stuffed animals",
    brand: "disney"
  },
  {
    product_id: "PR51012",
    name: "Pacific Play Tent Agility Dog Training Chute",
    price: 4373.13,
    stock: 7163,
    rating: 2.8,
    weight: 98,
    dimensions: "36cm L x 78cm W x 58cm H",
    color: "Fuscia",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "lego"
  },
  {
    product_id: "PR96475",
    name:
      "Mrs. Grossman's Outer Space Reusable Sticker Activity Set, Multicolor",
    price: 3994.31,
    stock: 4950,
    rating: 2.8,
    weight: 16,
    dimensions: "26cm L x 68cm W x 07cm H",
    color: "Blue",
    age: "10+",
    category: "action figures & playsets",
    brand: "lego"
  },
  {
    product_id: "PR09028",
    name:
      "Click N' Play Jumbo 10.5” Animal Figurine Playset, Assorted 5Piece Realistically Designed Wild Zoo, Safari, Jungle Plastic Animals for Kids & Toddlers",
    price: 2721.59,
    stock: 2560,
    rating: 2.9,
    weight: 78,
    dimensions: "00cm L x 07cm W x 93cm H",
    color: "Indigo",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "disney"
  },
  {
    product_id: "PR82013",
    name:
      "Transformers TCG: Bumblebee Vs. Megatron 2-Player Starter Set | 1 Ready-to-Play Deck | 44 Cards Incl. Bumblebee",
    price: 4583.38,
    stock: 641,
    rating: 2.2,
    weight: 83,
    dimensions: "90cm L x 33cm W x 97cm H",
    color: "Mauv",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "play-doh"
  },
  {
    product_id: "PR84158",
    name: "Disney Pixar Cars Deluxe Van Scanlane",
    price: 1818.9,
    stock: 9923,
    rating: 0.7,
    weight: 87,
    dimensions: "50cm L x 78cm W x 55cm H",
    color: "Puce",
    age: "7-10",
    category: "games & puzzles",
    brand: "barbie"
  },
  {
    product_id: "PR56665",
    name: "Sugarbooger Silicone Teether Set-of-Two, Happy Cactus",
    price: 1774.17,
    stock: 9254,
    rating: 0.3,
    weight: 36,
    dimensions: "32cm L x 28cm W x 24cm H",
    color: "Green",
    age: "7-10",
    category: "baby, toddler, & preschool learning toys",
    brand: "barbie"
  },
  {
    product_id: "PR70492",
    name:
      "Creativity for Kids My First Fun Felt Shapes - Travel Friendly Felt Board for Toddlers (Imaginative Pretend Play for Kids, 100+Piece)",
    price: 1818.23,
    stock: 67,
    rating: 2.1,
    weight: 24,
    dimensions: "17cm L x 76cm W x 95cm H",
    color: "Crimson",
    age: "3-6",
    category: "vehicles and remote controls",
    brand: "marvel"
  },
  {
    product_id: "PR43482",
    name: "Peppa Pig Shape Sorter Clock Puzzle (12Piece)",
    price: 858.19,
    stock: 3294,
    rating: 2.6,
    weight: 35,
    dimensions: "30cm L x 50cm W x 71cm H",
    color: "Purple",
    age: "0-2",
    category: "vehicles and remote controls",
    brand: "others"
  },
  {
    product_id: "PR82959",
    name:
      "GUND Baby My First Christmas Reindeer Lovey Plush Blanket, 12, Brown",
    price: 2840.32,
    stock: 8000,
    rating: 1.4,
    weight: 61,
    dimensions: "56cm L x 63cm W x 20cm H",
    color: "Aquamarine",
    age: "7-10",
    category: "action figures & playsets",
    brand: "others"
  },
  {
    product_id: "PR70706",
    name:
      "PLUS PLUS - Construction Building Toy, Open Play Set - 3,600 Pieces with Storage Tub - Basic Color Mix",
    price: 1419.26,
    stock: 7029,
    rating: 1,
    weight: 84,
    dimensions: "65cm L x 10cm W x 04cm H",
    color: "Yellow",
    age: "7-10",
    category: "vehicles and remote controls",
    brand: "others"
  },
  {
    product_id: "PR17503",
    name:
      "Canal Toys Power Dough Unicorns Interactive Dough (11Piece), Multicolor",
    price: 3565.37,
    stock: 936,
    rating: 2.9,
    weight: 86,
    dimensions: "26cm L x 55cm W x 51cm H",
    color: "Orange",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "disney"
  },
  {
    product_id: "PR06001",
    name:
      "NKOK Ghostbusters Animated B/O Ecto1 with Slimer B/O 1, Ghost Catcher",
    price: 1452.12,
    stock: 1486,
    rating: 1.4,
    weight: 40,
    dimensions: "18cm L x 46cm W x 68cm H",
    color: "Blue",
    age: "7-10",
    category: "kids arts and crafts",
    brand: "hot wheels"
  },
  {
    product_id: "PR60875",
    name: "Perler Beads Forest Animals Fuse Bead Kit, 2000pcs, 7 Projects",
    price: 4160.11,
    stock: 8977,
    rating: 2.2,
    weight: 23,
    dimensions: "97cm L x 94cm W x 04cm H",
    color: "Crimson",
    age: "7-10",
    category: "dolls, collectibles, and stuffed animals",
    brand: "hot wheels"
  },
  {
    product_id: "PR29635",
    name:
      "Loftus SW-0249 4 Pc Classic Wooden Games in A Tin Set, 6 inches Long, Brown",
    price: 2474.9,
    stock: 5137,
    rating: 0.6,
    weight: 94,
    dimensions: "55cm L x 40cm W x 58cm H",
    color: "Teal",
    age: "3-6",
    category: "kids arts and crafts",
    brand: "play-doh"
  },
  {
    product_id: "PR23360",
    name:
      "Bachmann EMD 70ACe DCC Sound Value Equipped Diesel Locomotive - ILLINOIS TERMINAL #1072 (with operating ditch lights) - HO Scale",
    price: 1289.37,
    stock: 7805,
    rating: 2.9,
    weight: 69,
    dimensions: "53cm L x 18cm W x 53cm H",
    color: "Crimson",
    age: "10+",
    category: "dolls, collectibles, and stuffed animals",
    brand: "play-doh"
  },
  {
    product_id: "PR92866",
    name: 'Hampton Nautical Wooden Charles W. Morgan Model Whaling Boat, 15"',
    price: 1972.81,
    stock: 49,
    rating: 3.4,
    weight: 34,
    dimensions: "07cm L x 94cm W x 66cm H",
    color: "Purple",
    age: "7-10",
    category: "vehicles and remote controls",
    brand: "hot wheels"
  },
  {
    product_id: "PR50705",
    name: 'Strawberry Shortcake Classic Doll, 6"',
    price: 3268.41,
    stock: 9707,
    rating: 3.4,
    weight: 100,
    dimensions: "03cm L x 26cm W x 77cm H",
    color: "Mauv",
    age: "3-6",
    category: "vehicles and remote controls",
    brand: "funko"
  },
  {
    product_id: "PR64131",
    name: "Originals Aquaman DC Comics Superman Zombie String Doll Keychain",
    price: 2492.4,
    stock: 8992,
    rating: 2,
    weight: 60,
    dimensions: "38cm L x 23cm W x 84cm H",
    color: "Aquamarine",
    age: "0-2",
    category: "kids arts and crafts",
    brand: "play-doh"
  },
  {
    product_id: "PR15449",
    name: "Disney Pixar Cars Deluxe Van Scanlane",
    price: 1114.34,
    stock: 9923,
    rating: 3.4,
    weight: 87,
    dimensions: "48cm L x 65cm W x 83cm H",
    color: "Puce",
    age: "0-2",
    category: "building sets & blocks",
    brand: "others"
  },
  {
    product_id: "PR46781",
    name: "Edupress Common Core Task Cards, Language, Grade 6 (EP63354)",
    price: 506.18,
    stock: 4332,
    rating: 3.2,
    weight: 28,
    dimensions: "99cm L x 49cm W x 51cm H",
    color: "Mauv",
    age: "7-10",
    category: "baby, toddler, & preschool learning toys",
    brand: "play-doh"
  },
  {
    product_id: "PR49790",
    name: "Star Wars: The Force Awakens Child's Stormtrooper Costume, Medium",
    price: 1674.68,
    stock: 752,
    rating: 0.3,
    weight: 58,
    dimensions: "64cm L x 15cm W x 27cm H",
    color: "Turquoise",
    age: "3-6",
    category: "action figures & playsets",
    brand: "others"
  },
  {
    product_id: "PR17596",
    name: "Fisher-Price Infant-to-Toddler Rocker, Jungle Fun",
    price: 1481.54,
    stock: 8696,
    rating: 1.4,
    weight: 82,
    dimensions: "68cm L x 03cm W x 32cm H",
    color: "Pink",
    age: "3-6",
    category: "vehicles and remote controls",
    brand: "disney"
  },
  {
    product_id: "PR97227",
    name:
      "Melissa & Doug Children’s Book - Float-Alongs: Tiny Tugboats (Bath Book + 3 Floating Tugboat Toys, Great Gift for Girls and Boys - Best for Babies and Toddlers, 4, 5, 9 Month Olds, 1 and 2 Year Olds)",
    price: 1298.19,
    stock: 9071,
    rating: 0.9,
    weight: 94,
    dimensions: "41cm L x 31cm W x 95cm H",
    color: "Violet",
    age: "10+",
    category: "dolls, collectibles, and stuffed animals",
    brand: "hot wheels"
  },
  {
    product_id: "PR90834",
    name:
      "Click N' Play Military Logistics Transport Unit 16 Piece Play Set with Accessories.",
    price: 2753.98,
    stock: 1996,
    rating: 4.1,
    weight: 18,
    dimensions: "22cm L x 72cm W x 29cm H",
    color: "Fuscia",
    age: "3-6",
    category: "baby, toddler, & preschool learning toys",
    brand: "barbie"
  },
  {
    product_id: "PR65432",
    name:
      "Paw Patrol, Mighty Pups Charged Up Chase’s Deluxe Vehicle with Lights and Sounds",
    price: 1415.91,
    stock: 1069,
    rating: 4.9,
    weight: 49,
    dimensions: "27cm L x 07cm W x 21cm H",
    color: "Aquamarine",
    age: "7-10",
    category: "action figures & playsets",
    brand: "disney"
  }
];
